/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    ChatCenter: typeof import('./src/components/chatwindow/center/chat-center.vue')['default']
    ChatFooter: typeof import('./src/components/chatwindow/footer/chat-footer.vue')['default']
    ChatHeader: typeof import('./src/components/chatwindow/header/chat-header.vue')['default']
    ChatWindow: typeof import('./src/components/chatwindow/ChatWindow.vue')['default']
    Content: typeof import('./src/components/chatwindow/content/Content.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/chatwindow/footer/Footer.vue')['default']
    FooterBootom: typeof import('./src/components/chatwindow/footer/footer-bottom/FooterBootom.vue')['default']
    FooterContent: typeof import('./src/components/chatwindow/footer/footer-content/FooterContent.vue')['default']
    FooterHeader: typeof import('./src/components/chatwindow/footer/foot-header/FooterHeader.vue')['default']
    Header: typeof import('./src/components/chatwindow/header/Header.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/sideBar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
